name: hello-world
on:
    push:
        branches:
            - main
jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: imprime mensaje
              run: echo "hello world"
            - name: fecha
              run: date
            - name: checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            



